//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoUtil {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CertificadosRsa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CertificadosRsa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoUtil.CertificadosRsa", typeof(CertificadosRsa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XChk6085lSL+/aFX2t1O0/cy14qC/Aw+cyQVXzrrD1519UW4gyoDFKdKKVzTEc/GOr8Er4Qtb3riepFkMW2jN7nSIbI6YnX0V2aHyG7A49D2a8C1kZJhwm1U9KHXPZRjJ0tV1q0ROerPeY2g5+nv2KHi7n0Mzt/0xLkBEn4eBAdOk/5J0tPGjdIZ1b5cnPHVW0V0ervFY7668+4y/MHZHxw3Ch6djd/qjMMvv805J2XfxDXL047/ZBzD0rw+bHrV3dPYfPFaYAXmR9/zJKNHV/Me1awE2oDEysU3KqtkfHfrtMNK9Q9x0qQlNC36msFAhELTIBWul1+XQgOg71nHbw==.
        /// </summary>
        internal static string KeyElement {
            get {
                return ResourceManager.GetString("KeyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN RSA PRIVATE KEY-----
        ///MIIEpAIBAAKCAQEApon3OffGTUnb+vzh7q/CmaPrS5XGpX4+5PcHqk7/nnMxVPP5
        ///RhOb1J8N35nXpmHK1/JApVasReq3V9Xd/SjjVCyAFwcAjAJGDCRYWCIxZ+yFfxFa
        ///QLo9bok9oWdp74oEe0ZQfWhfsAaKvClgV6AW3jfR8KALe/VhnZFlqaWFitmrP6c5
        ///E6vB00MstcvfRGfuKznUQOwn2o9PF7AdgtnaAuLc8+CRsi4XyMU/D4bz5Ct2KO50
        ///4xwGZsI+dVJWE2/ELjnkoDL7KfEQy8/JF176/zXfY2UlIppejILk2HkV10/TSlLX
        ///u09QJFALPZet/hndf0DWW1JFu3kvEkw4YuzfKwIDAQABAoIBAHBoURmsVwnV34gy
        ///ZiEgOv5O+MNkzdboNnV/E4ptlfWSFOsdXdRh6d2Cme+hvEAOY8aMOfwfW1o5yhSc
        ///QyDcF0y6WJ6yWDkoU7VgVszuD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PUBLIC KEY-----
        ///MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApon3OffGTUnb+vzh7q/C
        ///maPrS5XGpX4+5PcHqk7/nnMxVPP5RhOb1J8N35nXpmHK1/JApVasReq3V9Xd/Sjj
        ///VCyAFwcAjAJGDCRYWCIxZ+yFfxFaQLo9bok9oWdp74oEe0ZQfWhfsAaKvClgV6AW
        ///3jfR8KALe/VhnZFlqaWFitmrP6c5E6vB00MstcvfRGfuKznUQOwn2o9PF7Adgtna
        ///AuLc8+CRsi4XyMU/D4bz5Ct2KO504xwGZsI+dVJWE2/ELjnkoDL7KfEQy8/JF176
        ////zXfY2UlIppejILk2HkV10/TSlLXu09QJFALPZet/hndf0DWW1JFu3kvEkw4Yuzf
        ///KwIDAQAB
        ///-----END PUBLIC KEY-----.
        /// </summary>
        internal static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
    }
}
