//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoTestProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CertificadosTestRsa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CertificadosTestRsa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoTestProject.CertificadosTestRsa", typeof(CertificadosTestRsa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as/J+Lve76Mzc8jD54M3+hxRlR1mZ9WKC2ARQ5O1zi5+F60tn4a/C0OTjWKwffR8J1jjgLSzPToV4gyTO+yvdCs9LO1hUh2W0b7IJklEOeMc7iOyrVNIADRJfkN5rjPSuUJp8PwBvsxIV+QczcKMx/sBgmv6O2S1SOXeeWohv8VuOaqlCByfMzmgFQ0U+pz2NgOOLH7DaT9HAYJPFtQWZz4644YJinrf4lR2vIPIVUSKp3bYRF0EeBrxIG+dDwmuTzZrsMQnI9wz4/AubIYH0aH2GSa4bttnQnpdUOD6IvImGHTYoejAjukVh+VAUQdEolkgWYWd6tMDwSLH4vp4ZsBh7bkT7i5J4ek+ManhkF5YJiBK2MfGQ+T86kWqRe+13TEdTAi5zcqeyypXeQ+ymm3W7jFan3CHvw0PkVGTPHG5dwRtoPvyT8UzSUfAIy7ZIO6C8r5rfYq+QheyTQoSny9FOQPa6/Gn7WYZjnh0Zh4ugnVLSU0a
        ///f2RAc4/LTxf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FileElement {
            get {
                return ResourceManager.GetString("FileElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xgdgce7eSAIWponvkefqvcKC/cBesiWnzNz+KPjXESD2LZ4lkLgHcDY+mJwO3kLWZLfxKytCrXTDVXSm+YmEysuj84EGmVDxxlgTG2QkFtOK4OCfVQkdf+mneZplksLFFL9UHfVldmPtpmiFg04JhO94Wmaavcc1WV0qxu4m8DPajVr4AQNZ4gH7H4S/lCIskKrUoM5y0tgOop0tBtACgbPSd4O9Z9CTm6gMVWC5zQLth1eFOGF6IIDGK4dOoZL37Fqt9LQ45ROAe8/yN0Y9uUsVZwyUcgirK5jhs/6EjCMDsekQi3bS+1261EAtxfynqfoA+x8Z1c+ecUUfdLRuiQ==.
        /// </summary>
        internal static string KeyElement {
            get {
                return ResourceManager.GetString("KeyElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN RSA PRIVATE KEY-----
        ///MIIEpAIBAAKCAQEApon3OffGTUnb+vzh7q/CmaPrS5XGpX4+5PcHqk7/nnMxVPP5
        ///RhOb1J8N35nXpmHK1/JApVasReq3V9Xd/SjjVCyAFwcAjAJGDCRYWCIxZ+yFfxFa
        ///QLo9bok9oWdp74oEe0ZQfWhfsAaKvClgV6AW3jfR8KALe/VhnZFlqaWFitmrP6c5
        ///E6vB00MstcvfRGfuKznUQOwn2o9PF7AdgtnaAuLc8+CRsi4XyMU/D4bz5Ct2KO50
        ///4xwGZsI+dVJWE2/ELjnkoDL7KfEQy8/JF176/zXfY2UlIppejILk2HkV10/TSlLX
        ///u09QJFALPZet/hndf0DWW1JFu3kvEkw4YuzfKwIDAQABAoIBAHBoURmsVwnV34gy
        ///ZiEgOv5O+MNkzdboNnV/E4ptlfWSFOsdXdRh6d2Cme+hvEAOY8aMOfwfW1o5yhSc
        ///QyDcF0y6WJ6yWDkoU7VgVszuD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PUBLIC KEY-----
        ///MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApon3OffGTUnb+vzh7q/C
        ///maPrS5XGpX4+5PcHqk7/nnMxVPP5RhOb1J8N35nXpmHK1/JApVasReq3V9Xd/Sjj
        ///VCyAFwcAjAJGDCRYWCIxZ+yFfxFaQLo9bok9oWdp74oEe0ZQfWhfsAaKvClgV6AW
        ///3jfR8KALe/VhnZFlqaWFitmrP6c5E6vB00MstcvfRGfuKznUQOwn2o9PF7Adgtna
        ///AuLc8+CRsi4XyMU/D4bz5Ct2KO504xwGZsI+dVJWE2/ELjnkoDL7KfEQy8/JF176
        ////zXfY2UlIppejILk2HkV10/TSlLXu09QJFALPZet/hndf0DWW1JFu3kvEkw4Yuzf
        ///KwIDAQAB
        ///-----END PUBLIC KEY-----.
        /// </summary>
        internal static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
    }
}
